"""empty message

Revision ID: 336fc6ceb443
Revises: e15567342ae6
Create Date: 2025-07-27 18:03:20.981724

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '336fc6ceb443'
down_revision = 'e15567342ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('surgery_booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('clinical_images', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('admission_type', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('ward', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('indications', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('requirements', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('anaesthesia_type', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('position', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('estimated_duration', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('comorbidities', sa.Text(), nullable=True))

    with op.batch_alter_table('wound_care_plan', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dressing_protocol', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('phase', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('comorbidities', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('images', sa.Text(), nullable=True))
        batch_op.alter_column('plan',
               existing_type=sa.TEXT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('wound_care_plan', schema=None) as batch_op:
        batch_op.alter_column('plan',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_column('images')
        batch_op.drop_column('comorbidities')
        batch_op.drop_column('phase')
        batch_op.drop_column('dressing_protocol')

    with op.batch_alter_table('surgery_booking', schema=None) as batch_op:
        batch_op.drop_column('comorbidities')
        batch_op.drop_column('estimated_duration')
        batch_op.drop_column('position')
        batch_op.drop_column('anaesthesia_type')
        batch_op.drop_column('requirements')
        batch_op.drop_column('indications')
        batch_op.drop_column('ward')
        batch_op.drop_column('admission_type')
        batch_op.drop_column('clinical_images')

    # ### end Alembic commands ###
