"""empty message

Revision ID: 4409fd30bfc4
Revises: 336fc6ceb443
Create Date: 2025-07-27 18:03:35.836812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4409fd30bfc4'
down_revision = '336fc6ceb443'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('topics', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('moderator_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('presenter_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('meet_link', sa.String(length=512), nullable=True))
        batch_op.add_column(sa.Column('auto_generated', sa.Boolean(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['presenter_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['moderator_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('academic_event', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('auto_generated')
        batch_op.drop_column('meet_link')
        batch_op.drop_column('presenter_id')
        batch_op.drop_column('moderator_id')
        batch_op.drop_column('topics')

    # ### end Alembic commands ###
