"""empty message

Revision ID: b64306a10854
Revises: 4409fd30bfc4
Create Date: 2025-07-28 14:38:35.009374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b64306a10854'
down_revision = '4409fd30bfc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('percentage', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('recommendation', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('advice', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('score', schema=None) as batch_op:
        batch_op.drop_column('advice')
        batch_op.drop_column('recommendation')
        batch_op.drop_column('percentage')

    # ### end Alembic commands ###
